#
#	Makefile for dcmtls/tests
#



SHELL = /bin/sh
VPATH = ../include:../../config/include
srcdir = .
top_srcdir = ..
configdir = ../../config

include $(configdir)/Makefile.def


all:

check:

install:

clean:
	rm -f $(TRASH)

distclean:
	rm -f $(DISTTRASH)

dependencies:
